# This hasn't been tested or finished yet, and won't be until I can be bothered
# to set my CI up again. The steps that have been filled in should work, but
# YMMV, so don't blame me if this script kills your cat or summons the
# antichrist.

kind: pipeline
name: test_and_build

services:
- name: test-db
  image: mongo:5.0

steps:
- name: Install dependencies
  image: node:17
  commands:
    - yarn install --frozen-lockfile
- name: Build typescript
  image: node:17
  commands:
    - node_modules/.bin/tsc --resolveJsonModule
- name: Test w/ mocha
  image: node:17
  commands:
    - node_modules/.bin/cross-env NODE_ENV=test node_modules/.bin/mocha --exit
#- name: NYC Coverage
#  image: node:17
#  commands:
#    - node_modules/.bin/cross-env NODE_ENV=test node_modules/.bin/nyc node_modules/.bin/mocha
- name: Upload test results to S3
  image: plugins/s3
  settings:
    bucket: braze
    access_key: 
      from_secret: S3_AKEY
    secret_key:
      from_secret: S3_SKEY
    source: mochawesome-report/**/*
    target: /${DRONE_BRANCH}/mochawesome
#- name: Upload coverage to S3
#  image: plugins/s3
#  settings:
#    bucket: braze
#    access_key: 
#      from_secret: S3_AKEY
#    secret_key:
#      from_secret: S3_SKEY
#    source: coverage/**/*
#    target: /${DRONE_BRANCH}/coverage
#- name: Build docker image
#- name: Push docker image to repo
#- name: Notify Discord
