version: "3"
services:

  metal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /metal.config.js:/metal/metal.config.js:ro

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="true"
      - MYSQL_USER=metal
      - MYSQL_PASSWORD=Dontusethispassword
      - MYSQL_DATABASE=metal
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 20
    cap_add:
      - SYS_NICE

